# These are supported funding model platforms

github: [ebartile,] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: ebartile # Replace with a single Patreon username
